os: linux
dist: xenial
language: golang
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74.1/hugo_0.74.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.74.1_Linux-64bit.deb
script:
  - git submodule update --init
  - git submodule update --remote --merge
  - hugo -d ../generated
  
deploy:
  provider: pages
  cleanup: true
  strategy: git
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ../generated
  on:
    branch: master